### ISSUE TITLE
Request: Static map of all the fonts => Map<String, IconData>

### ISSUE THREAD

**Issue by exts** [fluttercommunity/font_awesome_flutter#102]
It would be cool if out the gate there was a way to find a icon name by it's string name from a list. Would open up the possibility for using font awesome icons in ways such as allowing users to select icons from a list then we could store their string name and directly call them from the map without needing to reflect the font awesome class or generating a map ourselves to do the same thing.

**Comment by michaelspiss** [comment]
Hi, we don't support icon maps officially, but you can use [this generator](https://www.github.com/fluttercommunity/font_awesome_flutter/tree/icon-map/tool%2Fgenerate_icon_map.dart) by calling it in the updater tool.
You will need a local installation of font awesome for this, please follow the instructions for pro icons and ignore everything that says copy/replace files.
If you need further assistance feel free to ask.

**Comment by michaelspiss** [comment]
Instead of using icon names, you could also just save the codePoint value and used icon style. This is actually the preferred method, because it ensures your app does not break should an icon name change (which happened with fa update 4.x to 5 for example).

For more information please refer to [these](https://github.com/fluttercommunity/font_awesome_flutter/issues/10) [discussions](https://github.com/fluttercommunity/font_awesome_flutter/pull/71).

**Comment by exts** [comment]
Alright, I'll give that a shot.

**Comment by michaelspiss** [comment]
For further reference: To build the app with flutter 1.22 and above, the flag `--no-tree-shake-icons` needs to be added to the build command when using this approach.
