### ISSUE TITLE
Doesn't work with Skia Web.

### ISSUE THREAD

**Issue by m-j-g** [fluttercommunity/font_awesome_flutter#103]
Icon images don't load when using FLUTTER_WEB_USE_SKIA=true.

This comment might or might not be useful:
https://github.com/flutter/flutter/issues/49725#issuecomment-581052213

cached_network_image and flutter_svg libraries both have working solutions now, which might be helpful.

In the meantime its not a big deal to just manually download the icons from font awesome and add them to the project.

**Comment by michaelspiss** [comment]
Hi, this package does not load images, but fonts (each icon is a symbol). So if icons don't display, it is probably a bug with skia custom font loading.
I'm leaving this open until I can investigate further, but it might take a while as I'm currently a bit short on spare time.

**Comment by m-j-g** [comment]
Oh, ok, interesting.

**Comment by MichealReed** [comment]
Wanted to report, this is not related to the network image issue. I took a brief look at the skia font handling, but don't see anything immediately apparent. I am only using a couple of icons from FontAwesome, so I will probably opt to move back to standard material icons until a fix is found here. Since this is not related to the above network image issue, if you don't see something on the FontAwesome side and issue should be opened in the flutter repo.

**Comment by michaelspiss** [comment]
Ok, so I finally got around to test this, but could not reproduce with flutter 1.22. @m-j-g could you confirm this is still happening?

**Comment by MichealReed** [comment]
Not sure what exactly, but something fixed this around a week ago. Feel free to close.

**Comment by michaelspiss** [comment]
Great, thanks for the quick reply!
