### ISSUE TITLE
Icon size is different

### ISSUE THREAD

**Issue by AR553** [fluttercommunity/font_awesome_flutter#169]
Icon size is different than the Material Icon size, had to provide different sizes for material icons and FontAwesomeIcons.

**Comment by michaelspiss** [comment]
Hi, font awesome icons have different sizes than material icons, which are always square. The problem is that sometimes the sizes between icons differ. That's why we cannot just scale them up or down so it works for everyone (we tried). The easiest way to fix this in your app is to wrap FaIcon in another widget which scales them to a point that works for your app. Then just use this new widget.
