### ISSUE TITLE
Executing "configurator.bat --dynamic"  creates  name_icon_mapping.dart with error 

### ISSUE THREAD

**Issue by tarafat** [fluttercommunity/font_awesome_flutter#188]
Could not format because the source could not be parsed:

line 7194, column 36 of lib\name_icon_mapping.dart: Expected to find '('.
     â•·
7194 â”‚ 'overline': const FontAwesomeIcons.duotoneOverline,
     â”‚                                    ^^^^^^^^^^^^^^^
     â•µ
line 7120, column 44 of lib\name_icon_mapping.dart: Expected to find '('.
     â•·
7120 â”‚ 'meh-rolling-eyes': const FontAwesomeIcons.duotoneMehRollingEyes,
     â”‚                                            ^^^^^^^^^^^^^^^^^^^^^
     â•µ
line 7567, column 41 of lib\name_icon_mapping.dart: Expected to find '('.
     â•·
7567 â”‚ 'star-shooting': const FontAwesomeIcons.duotoneStarShooting,
     â”‚                                         ^^^^^^^^^^^^^^^^^^^
     â•µ
line 6826, column 43 of lib\name_icon_mapping.dart: Expected to find '('.
     â•·
6826 â”‚ 'grin-beam-sweat': const FontAwesomeIcons.duotoneGrinBeamSweat,
     â”‚                                           ^^^^^^^^^^^^^^^^^^^^
     â•µ
line 6678, column 34 of lib\name_icon_mapping.dart: Expected to find '('.
     â•·
6678 â”‚ 'faucet': const FontAwesomeIcons.duotoneFaucet,
     â”‚                                  ^^^^^^^^^^^^^
     â•µ
line 6390, column 41 of lib\name_icon_mapping.dart: Expected to find '('.
     â•·
6390 â”‚ 'chart-pie-alt': const FontAwesomeIcons.duotoneChartPieAlt,
     â”‚                                         ^^^^^^^^^^^^^^^^^^
     â•µ
line 7344, column 36 of lib\name_icon_mapping.dart: Expected to find '('.
     â•·
7344 â”‚ 'repeat-1': const FontAwesomeIcons.duotoneRepeat1,
     â”‚                                    ^^^^^^^^^^^^^^
     â•µ
line 6527, column 41 of lib\name_icon_mapping.dart: Expected to find '('.
     â•·
6527 â”‚ 'compress-wide': const FontAwesomeIcons.duotoneCompressWide,
     â”‚                                         ^^^^^^^^^^^^^^^^^^^
     â•µ
line 6752, column 33 of lib\name_icon_mapping.dart: Expected to find '('.
     â•·
6752 â”‚ 'flute': const FontAwesomeIcons.duotoneFlute,
     â”‚                                 ^^^^^^^^^^^^
     â•µ
line 7497, column 40 of lib\name_icon_mapping.dart: Expected to find '('.
     â•·
7497 â”‚ 'snowboarding': const FontAwesomeIcons.duotoneSnowboarding,
     â”‚                                        ^^^^^^^^^^^^^^^^^^^
     â•µ
(1842 more errors...)

**Comment by gslender** [comment]
Me too... what's up with that?

**Comment by gslender** [comment]
Sorted it...

Remove the 'const' from the following line 307 in util/lib/main.dart 
```
      output.add("'${icon.name}': const FontAwesomeIcons.$iconName,");
```

**Comment by michaelspiss** [comment]
Thanks @gslender, I pushed a fix. No idea how that const got there, it makes absolutely zero sense

**Comment by gslender** [comment]
Are you able to run the flutter lints on the generated file?? as I believe it has other incorrect code that compiles, but fails dart lint analysis according to flutter dev guides

**Comment by michaelspiss** [comment]
`name_icon_mapping.dart` has no lint messages at all for me. The only lint messages are due to duplicate `const` keywords in `font_awesome_flutter.dart`, the usage of `print()` in the configurator (which can be ignored imho) and some "missing" const keywords for const constructors. Neither of those messages are errors, but only "info"

**Comment by gslender** [comment]
Agree but also disagree. The unnecessary const is one example that you can simply just remove from the generator. For me, this clutters the lint analysis because I use custom packages for Pro and its highly annoying to have this pollute the app. Is it really a big deal to remove unnecessary const keywords that are technically incorrect use of the language... 

Every new Flutter app now turns the flutter linter on by default, and when you use this library with Pro icons, you get 1,000s of warnings about poor style.. just annoying and fairly easy to add the linter and fix these.

Much like having a line that is `int a= 1; int b =a; int c= b;` all technically fine but obviously poor programming to leave like that.

**Comment by gslender** [comment]
There is also lint issues in fa_duotone_icon.dart and fa_icon.dart

**Comment by michaelspiss** [comment]
I only have a limited amount of time to work on this project, so I mainly focus on popular or breaking problems. Since this hasn't been discovered in over three years since this package has been released, whilst easy to fix, it is not high on my priority list.
However, I'd be more than happy to merge a pull request should you be willing to work on this!

**Comment by gslender** [comment]
Done!
