### ISSUE TITLE
v6 metadata update

### ISSUE THREAD

**Issue by CosmicPangolin** [fluttercommunity/font_awesome_flutter#191]
Just spoke with a FontAwesome rep. They have no current intention of adding the metadata folder back into the zip file, and instead suggest querying for it through their GraphQL endpoint. Probably worth posting complete instructions in README.

https://fontawesome.com/v5.15/how-to-use/graphql-api/intro/getting-started

**Comment by michaelspiss** [comment]
Thanks for asking them and providing this information to us. Not sure how to feel about this, but at least it is a way to query for some of the required information.
From what I can see we will definitely lose search terms, as they cannot be retrieved through this api.

**Comment by CosmicPangolin** [comment]
Yeah I found this stance surprising.

**Comment by gslender** [comment]
I received this update from the FontAwesome support team, so it isn't set in stone yet about what they'll be providing in terms of the icons.json or similar...

`We are re-evaluating as a company what we've done with the metadata. We haven't made the decision yet but we'll let you know as soon as we do.`

**Comment by ryanawhelan** [comment]
I think you can pull everything needed from the API except search terms.  I have written some code to pull all free or pro icon data from their API and generate the font_awesome_flutter.dart from that instead of the icons.json.  You can still use icons.json if you have it (--no-api), but even when they provided it, it was a little flaky.    If you use API, the search terms are just blank since none are provided.

**Comment by devj3ns** [comment]
This can be closed because of the new release https://github.com/fluttercommunity/font_awesome_flutter/releases/tag/10.0.0 :)
