### ISSUE TITLE
Cannot run configurator on mac

### ISSUE THREAD

**Issue by rohnsht** [fluttercommunity/font_awesome_flutter#207]
I am not able to run ./configurator.sh on Mac Terminal.

**Comment by Davi-Silva** [comment]
Custom icons.json found, generating files
Duotone icons are no longer supported. Automatically disabled them.

Generating icon definitions
Formatted no files in 0.83 seconds.
Could not format because the source could not be parsed:

line 37560, column 23 of lib/font_awesome_flutter.dart: Expected a class member.
      ╷
37560 │ static const IconData 100 = hundredPoints;
      │                       ^^^
      ╵
line 37560, column 27 of lib/font_awesome_flutter.dart: Methods must have an explicit list of parameters.
      ╷
37560 │ static const IconData 100 = hundredPoints;
      │                           ^
      ╵
line 37560, column 27 of lib/font_awesome_flutter.dart: Operator declarations must be preceded by the keyword 'operator'.
      ╷
37560 │ static const IconData 100 = hundredPoints;
      │                           ^
      ╵
line 37560, column 29 of lib/font_awesome_flutter.dart: A function body must be provided.
      ╷
37560 │ static const IconData 100 = hundredPoints;
      │                             ^^^^^^^^^^^^^
      ╵
line 37560, column 14 of lib/font_awesome_flutter.dart: Expected to find ';'.
      ╷
37560 │ static const IconData 100 = hundredPoints;
      │              ^^^^^^^^
      ╵
line 37560, column 29 of lib/font_awesome_flutter.dart: Variables must be declared using the keywords 'const', 'final', 'var' or a type name.
      ╷
37560 │ static const IconData 100 = hundredPoints;
      │                             ^^^^^^^^^^^^^
      ╵
line 37560, column 27 of lib/font_awesome_flutter.dart: The string '=' isn't a user-definable operator.
      ╷
37560 │ static const IconData 100 = hundredPoints;
      │                           ^
      ╵

Generating example code
Formatted example/lib/icons.dart
Formatted 1 file (1 changed) in 0.61 seconds.

Found and enabled the following icon styles:
brands, regular, solid, light, thin

Running "dart pub get"
Resolving dependencies...
  collection 1.15.0 (1.16.0 available)
  fake_async 1.2.0 (1.3.0 available)
  flutter_lints 1.0.4 (2.0.0 available)
  lints 1.0.1 (2.0.0 available)
  material_color_utilities 0.1.3 (0.1.4 available)
  path 1.8.0 (1.8.1 available)
  source_span 1.8.1 (1.8.2 available)
  test_api 0.4.8 (0.4.9 available)
  vector_math 2.1.1 (2.1.2 available)
Got dependencies!

Done

I'm running into this error while running /utils/configure.sh on Mac terminal after following the instructions for the pro icons version

**Comment by Davi-Silva** [comment]
There is a work around to this problem here #206  but it's really a solution.

**Comment by cryptozord** [comment]
> I am not able to run ./configurator.sh on Mac Terminal.

I had the same issue. I realized that I had to type "sh ./configurator.sh"

**Comment by michaelspiss** [comment]
I've added a FAQ entry about this. Thanks @cryptozord
