### ISSUE TITLE
[Feature] Pick icon from old version

### ISSUE THREAD

**Issue by EArminjon** [fluttercommunity/font_awesome_flutter#236]
**Is your feature request related to a problem? Please describe.**
It could be useful to have a package or a method which offer the possibility to specify the version of an icon. 
Icon can have a different look on some version. For example between 5 and 6 the shop icon look different.
Clients sometimes didn't like FontAwesome icons of the version 6 and prefer the old one.

Version 5
![Capture d’écran 2023-03-24 à 12 14 29](https://user-images.githubusercontent.com/37028599/227506971-33f2f6b4-5b1f-44e7-94ec-4fe1240ac9bc.png)

Version 6
![Capture d’écran 2023-03-24 à 12 14 37](https://user-images.githubusercontent.com/37028599/227506976-df44e657-6f17-451f-a0eb-b0c710c424ee.png)

**Describe the solution you'd like**
It could be great to expose something like FontAwesomeIcons6 and FontAwesomeIcons5 class.

**Describe alternatives you've considered**
Download manually the SVG file of the old icon.  It increase complexity and refactoring. Sometime we use icon, sometime image...

**Additional context**
None

**Comment by michaelspiss** [comment]
Hey @EArminjon! I have been thinking about this for a long time now. I can see the use case, but it's too niche to justify the amount of work required to make it a feature officially supported by this package.

Since it is open source, you are however welcome to just use any previous version of this package and rename it and the icons class to for example `font_awesome_flutter_five` and `FontAwesomeFiveIcons`. This way you can have both versions and icon tree shaking removes all unused icons automatically. Hope this helps whenever the need arises again in the future.
