### ISSUE TITLE
Size not consistent with material design icons

### ISSUE THREAD

**Issue by joshmatta** [fluttercommunity/font_awesome_flutter#31]
Fontawesome icons are little bigger than Icons in material/package
Can you make them same size so its consistent across the app
There is a little padding around icons in material package

**Comment by brianegan** [comment]
Hey there -- unfortunately I don't quite think that'd be possible, since the font itself comes from original FontAwesome team and Flutter is rendering that as-is. Also, since I don't know exactly what you're going for and if that'd work for everyone in the community, it might be tough to make it work for the wider audience.

As an alternative, you could create a custom Widget that accepted an Icon as a parameter and sets the correct font size / padded according to make it work for your design!

**Comment by ZAYEC77** [comment]
@brianegan 
I'm not sure about all icons but have found an issue with a coffee icon.
Here is an example of two icons:
- `Icons.shopping_basket`
- `FontAwesomeIcons.coffee`

I have wrapped it  to a colored container to show sizes:

![image](https://user-images.githubusercontent.com/4509483/59157174-e0aeb780-8aae-11e9-920b-47ab05650384.png)

I guess it's not a problem with this repo, but since I used it, I reported it here at first. 
Should I create an issue at FontAwesome repo, what do you think?

**Comment by ZAYEC77** [comment]
Although not, I found the same issue with other icons:
![image](https://user-images.githubusercontent.com/4509483/59157277-9deddf00-8ab0-11e9-9581-99172864cb72.png)

**Comment by jamesblasco** [comment]
Same problem for me

<img width="40" alt="Captura de pantalla 2019-09-15 a las 14 19 03" src="https://user-images.githubusercontent.com/19904063/64921467-d2fe8180-d7c3-11e9-869c-450e382c8b03.png">

I think If you give a size to an icon it shouldn’t exceed the edges

**Comment by jamesblasco** [comment]
Okey, apparently  is a Flutter problem => https://github.com/flutter/flutter/issues/34958

**Comment by magpiedigital** [comment]
I don't think it's impossible to do. The material icons appear to be 75% of the size of the font awesome icons, so in the `FaIcon` widget, instead of inheriting the default IconTheme size, you inherit 75% of the default IconTheme size.

**Comment by michaelspiss** [comment]
This was discussed way before `FaIcon` was a thing. You are right, this issue can be fixed with the steps you described above - reopening (providing a fix as soon as my schedule allows)

**Comment by magpiedigital** [comment]
Awesome. I edited the code and did the same thing and for the most part it works, however the size discrepancy does vary a bit but for the most part I think a value of 75% - 85% does the job.

**Comment by NuclleaR** [comment]
I have the same problem

**Comment by michaelspiss** [comment]
Material icons are all set within squares, font awesome icons within rectangles. This is why they don't work well together and why we need a special `FaIcon` class instead of material's `Icon`. There is nothing we can do about the geometric differences. It's actually not even a bug, it's intentional.

For the size discrepancy we could add an attribute which multiplies the size with .75 for example. The same result can be obtained by simply wrapping the `FaIcon` in a widget which sets the icon's `size` parameter to the value needed. In the spirit of keeping the api as clean and as close to the original `Icon` as possible, the latter is the recommended way.

Marking this as wontfix.
