### ISSUE TITLE
How to use Font awesome Pro Icons?

### ISSUE THREAD

**Issue by ParsaGachkar** [fluttercommunity/font_awesome_flutter#51]
I've got font awesome pro files. Can i add font awesome pro icons to this package too? If yes please guide me.

**Comment by michaelspiss** [comment]
I issued a pull request (#37) to add support for pro icons in april, but it sadly hasn't been merged yet. You can clone it from https://github.com/michaelspiss/font_awesome_flutter, further instructions are in the readme. I couldn't work on duotone icons because my license expired a week before the update, but all other icons work fine. If you have any problems just hit me up :)

**Comment by kornji** [comment]
me too, it's not work on duotone.

**Comment by michaelspiss** [comment]
I currently don't have enough money to spend it on another font awesome pro license, so I sadly cannot work on duotone icons (even though I gladly would, they look pretty cool)

**Comment by johnyluyte** [comment]
https://github.com/brianegan/font_awesome_flutter/issues/17#issuecomment-530550589

This comment might help a bit (as workaround).

**Comment by brianegan** [comment]
Pro icon support has landed, thanks @michaelspiss -- I'll be publishing a new version shortly.

**Comment by Nitingadhiya** [comment]
@brianegan is it available now? 
because we also tried to follow override font awesome package but it's not working.

**Comment by drmspatil** [comment]
> @brianegan is it available now?
> because we also tried to follow override font awesome package but it's not working.

Overide Not working
