### ISSUE TITLE
Web: wide icons (like desktop, pc, code) are cut on the right

### ISSUE THREAD

**Issue by scognito** [fluttercommunity/font_awesome_flutter#67]
They work on mobile, but are cut on web.

Sample code:
`Icon(
          FontAwesomeIcons.desktop,
          size: 30,
          color: Colors.black,
        )`

Attached the example (third icon working correctly, added for reference)

![icons](https://user-images.githubusercontent.com/466004/71778951-48c96b80-2fb4-11ea-8e42-7808ba1b8cf5.PNG)

**Comment by edufolly** [comment]
I have the same issue.

**Comment by brianegan** [comment]
Hey all -- I'll update the docs. The `Icon` Widget sets a specific, square size for Icons. The Material Icons fit into this pattern, but the Font Awesome Icons do not (some are wider than they are tall, many are not perfect squares).

Enough folks have run into this that I might go ahead and make a special Widget for this library that does not assume the box will be square.

As a workaround for now, use the `Text` Widget to render icons instead of the `Icon` Widget:

```dart
Text(String.fromCharCode(icon.iconData.codePoint),
    style: TextStyle(fontSize: 36.0, fontFamily: icon.iconData.fontFamily, package: icon.iconData.fontPackage)
  )
```

**Comment by brianegan** [comment]
Hi there -- please use the new `FaIcon` Widget in place of the `Icon` Widget -- it'll handle all of this for ya!
