### ISSUE TITLE
Problem font_awesome_flutter flutter web

### ISSUE THREAD

**Issue by ederluca** [fluttercommunity/font_awesome_flutter#72]
I have a small problem with the font_awesome_flutter package I added the same to my pubspec.yaml file in dev_dependecies I am running a web project when I run the debug I get the message:

Unable to find modules for some sources, this is usually the result of either a
bad import, a missing dependency in a package (or possibly a dev_dependency
needs to move to a real dependency), or a build failure (if importing a
generated file).

I already changed pubspec.yaml in place of dev_dependecies in dependencies and nothing would like to know if the package is compatible with web flutter projects

**Comment by brianegan** [comment]
Hi @ederluca  -- I think Flutter web is a bit of a moving target right now since it's in beta, but I've managed to test the Example app with the latest version of Flutter and it seems to have worked!

I've just pushed up the latest version of the example with Support for the Flutter beta branch an the Example seems to work on Chrome for me (didn't test other browsers).

Could you please give that a shot and let me know if you run into trouble?
